spring:
    mail:
      host: smtp.gmail.com
      port: 587
      username: cdm2153@gmail.com
      password: ahmgxwfvfteauenp
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
    application:
        name: NOTIFICATION-SERVICE
    kafka:
      bootstrap-servers: localhost:9092
      template:
        default-topic: order-events
      consumer:
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        properties:
          spring:
            json:
              type:
                mapping: order:com.minhvu.notificationservice.event.OrderPlaceEvent
        group-id: notification-group-id


eureka:
  client:
    service-url:
        defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

server:
    port: 0