spring:
  application:
    name: CHAT-SERVICE
  data:
    mongodb:
      username: mongo
      password: mongo
      host: localhost
      port: 27017
      database: chat-service
      authentication-database: admin

server:
  port: 8080

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761