version: '3'
services:
  data:
    container_name: data
    image: postgres:12-alpine
    ports:
      - "5430:5430"
    expose:
      - 5430
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    command: -p 5430

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    volumes:
      - pgadmin4_data:/var/lib/pgadmin4/data
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    ports:
      - "5050:80"
    depends_on:
      - data



volumes:
  pgadmin4_data: { }