server:
  port: 9296

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: REGISTRY-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/eureka

        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**

        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/products/**
          filters:
            - AuthenticationFilter

        - id: INVENTORY-SERVICE
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/v1/inventory/**
          filters:
            - AuthenticationFilter

        - id: ENERGY-SERVICE
          uri: lb://ENERGY-SERVICE
          predicates:
            - Path=/api/v1/energy/**
          filters:
            - AuthenticationFilter

        - id: ORDER-SERVICE
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - AuthenticationFilter
